spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: false
    prefix: classpath:/templates/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: koopapapa

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

comment.avatar: https://attach.setn.com/newsimages/2020/03/25/2471791-XXL.jpg
server:
  port: 8081



